version: '3.8'

networks:
  my-network:
    driver: bridge


services:
  backend:
    image: ${IMAGE_FULL_PATH}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    networks:
      - "my-network"
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      - "8080"
    environment:
      - TZ=Asia/Seoul
    networks:
      - "my-network"

  nginx:
    image: "nginx:alpine"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx.conf 파일은 컨테이너 생성 시 자동으로 생성되는 기본 nginx.conf 파일을 그대로 사용
      # 기본 default.conf 파일을 커스텀한 default.conf 파일로 마운트
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - certbot
    environment:
      - TZ=Asia/Seoul
    networks:
      - "my-network"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet && nginx -s reload; sleep 12h & wait $${!}; done;'"
