#!/bin/sh

stagedFiles=$(git diff --staged --name-only)

echo "Running spotlessApply..."
./gradlew spotlessApply

if [ $? -ne 0 ]; then
  echo "Spotless apply failed!"
  exit 1
fi

# Add files to stage spotless applied
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done