name: develop pull request Check and Test (CI)

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
        distribution: [ 'temurin' ]

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # Secrets ENV GITHUB_ENV 등록
      - name: Load ENV into Environment Variable
        run: echo "${{ secrets.ENV }}" >> $GITHUB_ENV

      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Run container # 테스트 시에 레디스 필요
        run: docker compose -f ./docker-compose-test.yml up -d

      # Gradlew 생행 권한 허용
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      # Gradle setup
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}