name: develop Deploy

on:
  # 워크플로우를 수동으로 트리거, 수동 배포
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "commit hash"
        required: true

env:
  DOCKERHUB_USERNAME: shyeonpk
  DOCKERHUB_IMAGE_NAME: github-actions-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKERHUB_IMAGE_FULL_PATH: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.event.inputs.commit_hash }}
          DOCKERHUB_IMAGE_NAME: ${{ env.DOCKERHUB_IMAGE_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_IMAGE_FULL_PATH, DOCKERHUB_IMAGE_NAME
          debug: true
          script: |
            echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker compose up -d
            docker image prune -a -f

      - name: Send to slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Build and Deploy result"
            blocks: 
              - type: section
                text:
                  type: mrkdwn
                  text: "*✅ 배포 완료 알림*"
              - type: section
                fields:
                  - type: mrkdwn
                    text: "*브랜치:* `${{ github.ref_name }}`"
                  - type: mrkdwn
                    text: "*커밋:* `${{ github.event.inputs.commit_hash.substr(0, 7) }}`"
              - type: context
                elements:
                  - type: mrkdwn
                    text: "*커밋 링크:* <https://github.com/${{ github.repository }}/commit/${{ github.event.inputs.commit_hash }}|🔗 ${{ github.event.inputs.commit_hash.substr(0, 7) }}>"
                  - type: mrkdwn
                    text: "*실행 로그:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|🔗 ${{ github.run_id }}>"